apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority: /etc/kubernetes/pki/ca.crt
    server: https://104.248.83.162:6443
  name: newwonderful-cluster
users:
- name: moo
  user:
    client-certificate: /root/certs/scripts/moo.crt
    client-key: /root/certs/scripts/moo.key
contexts:
- context:
    cluster: newwonderful-cluster
    namespace: default
    user: moo
  name: default-context
preferences: {}
current-context: default-context
