apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: #CACRT_DATA
    server: #SERVERADDRESS
  name: #CLUSTERNAME
users:
- name: #USERNAME
    user: 
      client-certificate-data: #CLIENTCRT_DATA
      client-key-data: #CLIENTKEY_DATA
