apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority: #CACRT_FILE
    server: #SERVERADDRESS
  name: #CLUSTERNAME
users:
- name: #USERNAME
    user: 
      client-certificate: #CLIENTCRT_FILE
      client-key: #CLIENTKEY_FILE
